version: '3.8'

services:
  # Backend API Server
  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: retell-backend
    restart: unless-stopped
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - PORT=3001
    env_file:
      - .env
    networks:
      - retell-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3001/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Frontend (for development)
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: retell-frontend
    restart: unless-stopped
    ports:
      - "5173:80"
    depends_on:
      - backend
    networks:
      - retell-network
    volumes:
      - ./dist:/usr/share/nginx/html:ro

  # Nginx Reverse Proxy
  nginx:
    image: nginx:alpine
    container_name: retell-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/sites-enabled:/etc/nginx/sites-enabled:ro
      - ./dist:/var/www/retell-widget/dist:ro
      - ./nginx/ssl:/etc/nginx/ssl:ro
    depends_on:
      - backend
    networks:
      - retell-network

networks:
  retell-network:
    driver: bridge
